version: "3"
services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      - VITE_APP_API_URL=http://localhost:3000/api

networks:
  app-network:
    external: true
